name: Build and Push

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: "github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'chore: release version')"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noNewCommitBehavior: current
          noVersionBumpBehavior: current

      - name: Build images
        if: "github.ref != 'refs/heads/main' || !startsWith(github.event.head_commit.message, 'chore: release version')"
        env:
          CONTROLLER_IMG: ghcr.io/${{ github.repository_owner }}/pubip-operator-controller:${{ steps.semver.outputs.next }}
          FETCHER_IMG: ghcr.io/${{ github.repository_owner }}/pubip-operator-fetcher:${{ steps.semver.outputs.next }}
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            make docker-buildx PUSH=true CONTROLLER_IMG=${CONTROLLER_IMG} FETCHER_IMG=${FETCHER_IMG}
          else
            make docker-buildx
          fi

      - name: Build and push images
        if: "github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'chore: release version')"
        env:
          CONTROLLER_IMG: ghcr.io/${{ github.repository_owner }}/pubip-operator-controller:${{ steps.semver.outputs.next }}
          FETCHER_IMG: ghcr.io/${{ github.repository_owner }}/pubip-operator-fetcher:${{ steps.semver.outputs.next }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" && "${{ github.event.head_commit.message }}" == "chore: release version"* ]]; then
            make docker-buildx PUSH=true CONTROLLER_IMG=${CONTROLLER_IMG} FETCHER_IMG=${FETCHER_IMG}
          else
            make docker-buildx
          fi

  chart:
    if: "github.ref == 'refs/heads/main' && startsWith(github.event.head_commit.message, 'chore: release version')"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm installation
        run: helm version

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          noNewCommitBehavior: current
          noVersionBumpBehavior: current

      - name: Publish Helm chart
        env:
          CHART_VERSION: ${{ steps.semver.outputs.next }}
        run: |
          helm package ./dist/chart --version ${CHART_VERSION} --app-version ${CHART_VERSION}
          helm push pubip-operator-${CHART_VERSION}.tgz oci://ghcr.io/${{ github.repository_owner }}/pubip-operator/charts
